//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public int ID { get; set; }
        public string nameCar { get; set; }
        public string trongtai { get; set; }
        public string dongco { get; set; }
        public string kichthuocthung { get; set; }
        public string baohanh { get; set; }
        public Nullable<bool> hide { get; set; }
        public Nullable<int> order { get; set; }
        public string meta { get; set; }
        public Nullable<System.DateTime> datebegin { get; set; }
        public string img { get; set; }
        public string kltoanbo { get; set; }
        public string klbanthan { get; set; }
        public string sochongoi { get; set; }
        public string thungnhienlieu { get; set; }
        public string DxRxC { get; set; }
        public string chieudaicoso { get; set; }
        public string vetbanhxe { get; set; }
        public string khoangcachtruc { get; set; }
        public string tendongco { get; set; }
        public string loaidongco { get; set; }
        public string tieuchuankhithai { get; set; }
        public string dungtichxylanh { get; set; }
        public string congsuatcucdai { get; set; }
        public string momen { get; set; }
        public string hopso { get; set; }
        public string loainhieulieu { get; set; }
        public string phanhtruoc { get; set; }
        public string phanhsau { get; set; }
        public string phanhdong { get; set; }
        public string soluonglop { get; set; }
        public string lop { get; set; }
    }
}
