//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinTuc
    {
        public int id { get; set; }
        public string name { get; set; }
        public string img1 { get; set; }
        public string des1 { get; set; }
        public string link { get; set; }
        public string detail1 { get; set; }
        public string meta { get; set; }
        public Nullable<bool> hide { get; set; }
        public Nullable<int> order { get; set; }
        public Nullable<System.DateTime> datebegin { get; set; }
        public string img2 { get; set; }
        public string img3 { get; set; }
        public string des2 { get; set; }
        public string des3 { get; set; }
        public string detail2 { get; set; }
        public string detail3 { get; set; }
    }
}
